import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { MapPin, Phone, ShieldCheck, Truck, Wrench, Zap, type LucideIcon } from "lucide-react";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import HomeLongformContent from "@/components/HomeLongformContent";
import HomeSeoContent from "@/components/HomeSeoContent";
import JsonLd from "@/components/JsonLd";
import OperationGallery from "@/components/OperationGallery";
import ServiceAssurance from "@/components/ServiceAssurance";
import StickyCallBar from "@/components/StickyCallBar";
import { MAIN_PHONE, MAIN_PHONE_RAW } from "@/data/districts";
export const metadata: Metadata = { alternates: { canonical: "/" } };
const services: [string, string, string, LucideIcon][] = [["Oto Çekici", "Kayar kasa ile güvenli araç taşıma", "/oto-cekici", Truck], ["Akü Takviye", "Yerinde akü ve marş desteği", "/aku-takviye", Zap], ["Mobil Oto Elektrik", "Şarj ve elektrik arızalarında destek", "/oto-elektrik", Wrench]];
export default function HomePage() { return <><Header /><JsonLd /><main><section className="relative overflow-hidden bg-slate-950 text-white"><Image src="/izmir-cekici-hero.png" alt="İzmir çevre yolunda oto çekici" fill priority className="object-cover" /><div className="absolute inset-0 bg-slate-950/75" /><div className="relative container mx-auto max-w-6xl px-4 py-28"><p className="text-sm font-bold uppercase tracking-widest text-amber-300">7/24 İzmir oto çekici ve yol yardım</p><h1 className="mt-5 max-w-3xl font-heading text-5xl font-black leading-tight md:text-7xl">İzmir’de yolda kaldığınızda doğru ekip yanınızda.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Oto çekici, akü takviye, mobil oto elektrik, oto kurtarma ve ağır vasıta hizmetleri için İzmir genelinde konumunuza uygun ekip yönlendiriyoruz.</p><a href={`tel:${MAIN_PHONE_RAW}`} className="mt-8 inline-flex items-center gap-2 bg-amber-400 px-7 py-4 font-black text-slate-950"><Phone className="h-5 w-5" />{MAIN_PHONE}</a></div></section><section className="container mx-auto max-w-6xl px-4 py-20"><p className="text-sm font-bold uppercase tracking-widest text-amber-600">Hizmetlerimiz</p><h2 className="section-title mt-3">İzmir genelinde ihtiyaç duyduğunuz yol yardım hizmeti</h2><div className="mt-9 grid gap-5 md:grid-cols-3">{services.map(([title, text, href, Icon]) => <Link key={href} href={href} className="border border-slate-200 p-7 hover:border-amber-400"><Icon className="h-9 w-9 text-amber-500" /><h3 className="mt-5 font-heading text-2xl font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></Link>)}</div></section><section className="bg-slate-950 py-16 text-white"><div className="container mx-auto grid max-w-6xl gap-8 px-4 md:grid-cols-3"><p className="flex gap-3"><ShieldCheck className="text-amber-300" />Araç durumuna uygun ekipman seçimi</p><p className="flex gap-3"><MapPin className="text-amber-300" />İzmir’in tüm ilçe ve bölgelerinde hizmet</p><p className="flex gap-3"><Truck className="text-amber-300" />Kayar kasa, vinç ve kurtarıcı seçenekleri</p></div></section><HomeSeoContent /><ServiceAssurance /><OperationGallery /><HomeLongformContent /></main><Footer /><StickyCallBar /></>; }