import Link from "next/link";
import { CheckCircle2, MapPin } from "lucide-react";
type Props={district:string;serviceSlug:string;serviceTitle:string};
const notes:Record<string,[string,string[]]>={
"cekici":["Kayar kasa ile otomobil, SUV ve hafif ticari araç taşıma.",["Güvenli yükleme planı","Servis veya adrese transfer","Kaza ve arıza sonrası destek"]],
"oto-cekici":["Kayar kasa ile otomobil, SUV ve hafif ticari araç taşıma.",["Güvenli yükleme planı","Servis veya adrese transfer","Kaza ve arıza sonrası destek"]],
"aku-takviye":["Akü bitmesi, marş alma ve şarj belirtilerinde yerinde ilk destek.",["12V ve 24V sistemler","Bağlantı ve voltaj kontrolü","Gerekirse çekici yönlendirmesi"]],
"oto-elektrik":["Marş, şarj, akü ve temel elektrik arızalarında mobil değerlendirme.",["Marş sistemi ön kontrolü","Şarj belirtisi incelemesi","Güvenli servis transferi"]],
"agir-vasita-kurtarma":["Tır, kamyon ve otobüs için tonaj ve yol koşuluna uygun kurtarma planı.",["Uygun kurtarıcı seçimi","Otoyol ve sanayi alanı desteği","Güvenlik planlaması"]],
"agir-ticari-cekici":["Kamyon, panelvan ve ticari araçlar için güvenli çekici ile kontrollü transfer planlaması.",["Ticari araç tipine uygun ekipman","Sanayi, otoyol ve merkez bölge desteği","Güvenli yükleme ve teslim süreci"]],
"oto-kurtarma":["Kaza, şarampol ve zor konumlarda vinçli kurtarma değerlendirmesi.",["Kontrollü yükleme","Zor zeminlerde aparat seçimi","Güvenli transfer"]],
"lastik-yol-yardim":["Patlak lastik, stepne ve temel yol yardım ihtiyaçlarında yönlendirme.",["Güvenli konum bilgisi","Stepne desteği","Gerekirse çekici"]],
"motorsiklet-cekici":["Scooter, chopper, touring ve racing motosikletler için özel ön teker sabitleme takozu ve 4 noktalı yumuşak bağlama sapanı ile çiziksiz ve devrilme riski olmadan güvenli taşıma.",["Özel tekerlek kilitleme aparatı & takoz","4 noktalı yumuşak sapanla çiziksiz sabitleme","Yetkili servis veya adrese sigortalı transfer"]]};
export default function ServiceSeoContent({district,serviceSlug,serviceTitle}:Props){const[note,items]=notes[serviceSlug]||notes["cekici"]||notes["oto-cekici"];return <><section className="border-y border-slate-200 bg-white py-20"><div className="container mx-auto grid max-w-6xl gap-10 px-4 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-widest text-amber-600">{district} {serviceTitle}</p><h2 className="section-title mt-3">{district} için hizmet planı ve güvenli yönlendirme</h2><p className="mt-6 leading-8 text-slate-600" dangerouslySetInnerHTML={{__html:note}}/><p className="mt-4 leading-8 text-slate-600">{district} merkez, ana yollar ve çevre bölgelerde konum ile araç bilgisi değerlendirilir. Bu sayede ihtiyaca uygun ekipman ve hizmet seçeneği belirlenir.</p></div><aside className="bg-slate-950 p-8 text-white"><MapPin className="h-8 w-8 text-amber-300"/><h3 className="mt-4 font-heading text-2xl font-black">Hizmet kapsamı</h3><ul className="mt-6 space-y-4 text-sm text-slate-200">{items.map(item=><li key={item} className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-amber-300"/><span dangerouslySetInnerHTML={{__html:item}}/></li>)}</ul><Link href="/hizmet-bolgeleri" className="mt-8 inline-flex text-sm font-bold text-amber-300">Tüm hizmet bölgeleri</Link></aside></div></section><section className="bg-slate-100 py-16"><div className="container mx-auto max-w-6xl px-4"><p className="text-sm font-bold uppercase tracking-widest text-amber-600">Yerel hizmet rehberi</p><h2 className="section-title mt-3">{district} {serviceTitle} hakkında sık sorulan sorular</h2><div className="mt-8 grid gap-5 md:grid-cols-3"><article className="border border-slate-200 bg-white p-6"><h3 className="font-heading text-xl font-black">Hangi bilgiyle çağrı oluşturulur?</h3><p className="mt-3 text-sm leading-7 text-slate-600">Konum, araç tipi, arıza veya hasar durumu ve teslim adresi, uygun hizmet planını hızlandırır.</p></article><article className="border border-slate-200 bg-white p-6"><h3 className="font-heading text-xl font-black">Yönlendirme nasıl yapılır?</h3><p className="mt-3 text-sm leading-7 text-slate-600">Araç bilgisi ve bulunduğunuz yol koşulu değerlendirilerek ihtiyaca uygun ekipman seçeneği belirlenir.</p></article><article className="border border-slate-200 bg-white p-6"><h3 className="font-heading text-xl font-black">Araç nereye teslim edilir?</h3><p className="mt-3 text-sm leading-7 text-slate-600">Güvenlik değerlendirmesi sonrasında araç, talep edilen servis, iş yeri veya adrese kontrollü şekilde ulaştırılır.</p></article></div></div></section></>}